division: division.cpp division.s copy.s set_loop_size.s shifter.s arithmetic.s set_remainder.s
	g++ -g -m32 division.cpp division.s copy.s set_loop_size.s shifter.s arithmetic.s set_remainder.s -o division
